export const ActionTypes = {
  GET_PLAYERS: "GET_PLAYERS",
  CREATE_PLAYER: "CREATE_PLAYER",
  DELETE_PLAYER: "DELETE_PLAYER",
  UPDATE_PLAYER: "UPDATE_PLAYER",
  SAVE_VALUE:"SAVE_VALUE",
  FILTER_PLAYERS:"FILTER_PLAYERS"
};
